contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
theme: "ghostwriter"
category: "categories"
baseurl: "http://skarzee.github.io/"
title: "Hugo Blog Template for GitHub Pages"
canonifyurls: true